---
# multi-zabbix_agent/tasks/main.yml
# 

- name: "Downloading Package"
  get_url:
    url: http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+{{ ansible_distribution_release }}_all.deb
    dest: /tmp/zabbix-repository.deb
  tags:
    - zabbix-agent

- name: "Adding Zabbix repository key for Ubuntu"
  apt:
    deb: /tmp/zabbix-repository.deb
    state: present
  tags:
    - zabbix-agent

- name: "Installing dependencies - Ubuntu"
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - zabbix-agent
    - sysstat
  notify:
    - restart zabbix-agent
  tags:
    - zabbix-agent


- name: "Configuring Zabbix agent"
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
    force: yes
  notify:
    - restart zabbix-agent
  tags:
    - zabbix-agent

- name: "Creating LYONSCG custom Zabbix script directory"
  file:
    path: /etc/zabbix/scripts
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0755
  tags:
    - zabbix-agent

- name: "Remove bogus mysql file -- tags: zabbix-proxy"
  file:
    path: /etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf.dpkg-dist
    state: absent
  tags:
    - zabbix-agent

- name: "Adding Scripts to Zabbix"
  copy:
    src: "{{ item }}"
    dest: /etc/zabbix/scripts/
    owner: zabbix
    group: zabbix
    mode: 0755
    force: yes
  with_fileglob:
    - scripts/*
  notify:
    - restart zabbix-agent
  tags:
    - zabbix-agent

- name: "Adding Conf files to Zabbix"
  copy:
    src: "{{ item }}"
    dest: /etc/zabbix/zabbix_agentd.d/
    owner: root
    group: root
    mode: 0644
    force: yes
  with_fileglob:
    - conf/*
  notify:
    - restart zabbix-agent
    - enabled zabbix-agent
  tags:
    - zabbix-agent

- name: 'Start Zabbix Agent'
  command: systemctl start zabbix-agent
  become: true
  when: ansible_distribution_release == 'xenial'
  tags:
    - zabbix-agent

- name: 'Enabling Zabbix service on boot for Ubuntu 16.04.'
  command: systemctl enable zabbix-agent
  become: true
  when: ansible_distribution_release == 'xenial'
  tags:
    - zabbix-agent
