---
# web-php-ioncube/tasks/main.yml
- name: "Copying ionCube php configuration {{ php_processor }} for {{ ansible_distribution }} {{ ansible_distribution_release }} -- tags: ioncube"
  copy:
    src: /tmp/ioncube/ioncube_loader_lin_5.5.so
    dest: /usr/lib/php5/20121212/ioncube_loader_lin_5.5.so
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  when: 
    - php_processor | match('PHP-FPM|mod_php')
  tags:
    - ioncube

- name: "Setting ioncube.ini file -- tags: ioncube"
  copy:
    src: "{{ ansible_distribution }}_{{ ansible_distribution_release }}_ioncube.ini"
    dest: /etc/php5/mods-available/ioncube.ini
    owner: root
    group: root
    mode: 0644
  tags:
    - ioncube

- name: "Creating links for the ini files in apache2 -- tags: ioncube"
  file:
    src: ../../mods-available/ioncube.ini
    dest: /etc/php5/apache2/conf.d/01-ioncube.ini
    state: link
  when: 
    - php_processor | match('mod_php')
  tags:
    - ioncube

- name: "Creating links for the ini files in apache2 -- tags: ioncube"
  file:
    src: ../../mods-available/ioncube.ini
    dest: /etc/php5/fpm/conf.d/01-ioncube.ini
    state: link
  when:
    - php_processor | match('PHP-FPM')
  tags:
    - ioncube

- name: "Creating links for the ini files in cli -- tags: ioncube"
  file:
    src: ../../mods-available/ioncube.ini
    dest: /etc/php5/cli/conf.d/01-ioncube.ini
    state: link
  notify:
    - restart apache
  tags:
    - ioncube

######
#- name: "Enabling PHP icncube module -- tags: ioncube"
#  command: php5enmod ioncube
#  notify:
#    - restart apache
#  tags:
#    - ioncube
#
#- name: "Checking status of /etc/php5/apache2/conf.d/20-ioncube.ini -- tags: ioncube"
#  stat:
#    path:  /etc/php5/apache2/conf.d/20-ioncube.ini
#  register: a2ini 
#  tags:
#    - ioncube
#
#- name: "Checking status of /etc/php5/cli/conf.d/20-ioncube.ini -- tags: ioncube"
#  stat:
#    path:  /etc/php5/apache2/conf.d/20-ioncube.ini
#  register: cliini 
#  tags:
#    - ioncube

#- name: "Making sure ioncube loads first -- tags: ioncube"
#  command: mv 20-ioncube.ini 01-ioncube.ini
#  args:
#    chdir: /etc/php5/apache2/conf.d/
#  when: a2ini.stat.islnk is defined
#  tags:
#    - ioncube
#
#- name: "Making sure ioncube loads first -- tags: ioncube"
#  command: mv 20-ioncube.ini 01-ioncube.ini
#  args:
#    chdir: /etc/php5/cli/conf.d/
#  when: cliini.stat.islnk is defined
#  tags:
#    - ioncube
