# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook warner_prep.yml -Kk -i warner-hosts.ini

- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  tasks:
    - name: "Update files"
      replace:
        path: /etc/resolv.conf
        regexp: '10\.0\.1\.241'
        replace: '10.0.4.12'
        backup: yes
      with_items:
        - /etc/resolv.conf
        - /etc/network/interfaces
