---
# handlers/main.yml
- name: restart apache
  service:
    name: apache2
    state: restarted

- name: reload apache
  service:
    name: apache2
    state: reloaded

- name: restart php5-fpm
  service:
    name: php5-fpm
    state: restarted

- name: reload php5-fpm
  service:
    name: php5-fpm
    state: reloaded

- name: restart php7-fpm
  service:
    name: php7.0-fpm
    state: restarted

- name: reload php7-fpm
  service:
    name: php7.0-fpm
    state: reloaded

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: reload httpd
  service:
    name: httpd
    state: reloaded
