---
# db-mysql/defaults/main.yml

---
# defaults file
mysql_root_password: 'Rfvbgt345'
mysql_user: root
mysql_old_root_password: ''
mysql_root_password_init: ''
mysql_replication_user_password: Rfvbgt345
mysql_port: 3306

# GENERAL #
mysql_default_storage_engine: 'InnoDB'

# MyISAM #
mysql_key_buffer_size: 64M
mysql_myisam_recover: 'FORCE,BACKUP'
mysql_myisam_sort_buffer_size: 128M

# SAFETY #
mysql_max_allowed_packet: 16M
mysql_max_connect_errors: 1000000

# BINARY LOGGING #
mysql_log_bin: '/var/lib/mysql/mysql-bin'
mysql_sync_binlog: 1
mysql_binlog_format: MIXED
mysql_expire_logs_days: 7

# CACHES AND LIMITS #
mysql_tmp_table_size: 256M
mysql_max_heap_table_size: 256M
mysql_query_cache_type: 1
mysql_query_cache_size: 256M
mysql_query_cache_limit: 32M
mysql_max_connections: 200
mysql_thread_cache_size: 200
mysql_open_files_limit: 65535
mysql_table_definition_cache: 4096
mysql_table_open_cache: 4096

# INNODB #
mysql_innodb_flush_method: O_DIRECT
mysql_innodb_log_files_in_group: 3
mysql_innodb_log_file_size: 256M
mysql_innodb_flush_log_at_trx_commit: 2
mysql_innodb_file_per_table: 1
mysql_innodb_buffer_pool_size: 1G
mysql_innodb_log_buffer_size: 8M
mysql_innodb_additional_mem_pool_size: 20M
mysql_innodb_thread_concurrency: 0
mysql_innodb_io_capacity: 2000
mysql_innodb_buffer_pool_instances: 1
mysql_innodb_doublewrite: 0

# LOGGING #
mysql_log_error: /var/lib/mysql/mysql-error.log
mysql_log_queries_not_using_indexes: 0
mysql_slow_query_log: 1
mysql_slow_query_log_file: '/var/lib/mysql/mysql-slow.log'
mysql_long_query_time: 2

# BUFFERS #
mysql_read_buffer_size: 2M
mysql_read_rnd_buffer_size: 16M
mysql_sort_buffer_size: 8M
mysql_join_buffer_size: 32M
mysql_bulk_insert_buffer_size: 64M

#LCG OPTIONS
mysql_innodb_data_file_path: 'ibdata1:12M;ibdata2:128M:autoextend'
#mysql_server_id: 1
mysql_auto_increment_increment: 10
#mysql_auto_increment_offset: 1
mysql_interactive_timeout: 3600
mysql_wait_timeout: 3600
mysql_ignore_db_dir: lost+found
