---
# var-zabbix_agent/tasks/main.yml

- name: "Adding zabbix user to the varnish group"
  user:
    name: zabbix
    groups: varnish
    append: yes
  tags:
    - zabbix-agent

- name: "Adding Scripts to Zabbix"
  copy:
    src: "{{ item }}"
    dest: /etc/zabbix/scripts/
    owner: zabbix
    group: zabbix
    mode: 0755
    force: yes
  with_fileglob:
    - scripts/*
  notify:
    - restart zabbix-agent
  tags:
    - zabbix-agent

- name: "Adding Conf files to Zabbix"
  copy:
    src: "{{ item }}"
    dest: /etc/zabbix/zabbix_agentd.d/
    owner: root
    group: root
    mode: 0644
    force: yes
  with_fileglob:
    - conf/*
  notify:
    - restart zabbix-agent
  tags:
    - zabbix-agent
