---
# multi-zabbix_agent/handlers/main.yml
- name: restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted

- name: enabled zabbix-agent
  service:
    name: zabbix-agent
    enabled: yes
