---
# lb-haproxy/tasks/main.yml

- name: "Installing the HAProxy repository"
  apt_repository:
    repo: "ppa:vbernat/haproxy-1.6"
    state: present
    update_cache: yes
  when: ansible_distribution_release == 'trusty'

- name: "Installing HAProxy."
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - haproxy
    - hatop
    - socat

- name: 'Enabling HAProxy service on boot.'
  service:
    name: haproxy
    enabled: yes
    state: started
