#!/usr/bin/env ansible-playbook
---
# ci.yml

- hosts: CI
  vars_files:
    - vars.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  roles:
    - multi-java
    - multi-apache-install
    - multi-lcgosc-cert
    - ci-config-vhost
    - ci-jenkins
#    - ci-php
#    - ci-mysql
#    - ci-composer
#    - multi-zabbix_agent
#    - ci-zabbix_agent
#    - ci-graylog_collector
#    - ci-ufw
