#!/usr/bin/env ansible-playbook
---
# getconfig.yml
- hosts: localhost
  gather_facts: yes
  become: no
  tasks:
  - name: "checkout {{ client | lower }}{{ env_type | lower }}config"
    git:
      repo: "git@bitbucket.org:lyonsconsultinggroup/{{ client_code | lower }}{{ env_type | lower }}config.git"
      version: master
      dest: ./files/{{ client | lower }}{{ env_type | lower }}config
      accept_hostkey: yes
      force: yes

- hosts: LB
  vars_files:
    - files/{{ client | lower }}{{ env_type | lower }}config/vars.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  roles:
