#!/usr/bin/env ansible-playbook
---
# hybris.yml

- hosts: HYB
  vars_files:
    - vars.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  roles:
    - multi-apache-install
    - web-config-vhost
    - multi-lcgosc-cert
    - multi-java
    - hybris 
