#!/usr/bin/env ansible-playbook
---
# red.yml

- hosts: all
  vars_files:
    - vars.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  roles:
    - all-lvm
