#!/usr/bin/env ansible-playbook
---
# mem.yml

- hosts: MEM
  vars_files:
    - vars.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  roles:
#    - mem-memcached
#    - mem-zabbix_agent
#    - mem-graylog_collector
#    - mem-ufw