#!/usr/bin/env ansible-playbook
---
# mon.yml

- hosts: MON
  vars_files:
    - vars.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  roles:
    - db-mysql-install

- hosts: MON
  vars_files:
    - vars.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  roles:
    - multi-zabbix_agent
    - mon-zabbix_proxy
#    - mon-graylog_collector
#    - mon-ufw