#!/usr/bin/env ansible-playbook
---
# whl.yml

- hosts: WHL
  vars_files:
    - vars.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  roles:
    - multi-apache-install
#    - whl-zabbix_agent
#    - whl-graylog_collector
#    - whl-ufw
