- hosts: LB
  vars_files:
    - vars.yml
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  serial: 1
  tasks:
  - name: "Check if lsyncd is already installed -- tags: lsync, lsync-master"
    shell: dpkg -s lsyncd | grep 'install ok installed'
    register: is_installed
    failed_when: is_installed.rc > 1
    changed_when: no
    when:
      - lsync is defined
      - lsync is match("master")

  - debug:
#      msg: "{{ is_installed.rc }}"
      msg: "lsync is not installed "
    when:
      - lsync is defined
      - lsync is match("master")
      - is_installed.rc
    
  - debug:
#      msg: "{{ is_installed.rc }}"
      msg: "lsync is installed "
    when:
      - lsync is defined
      - lsync is match("master")
      - not is_installed.rc
