# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

#- hosts: DB:WEB
- hosts: RED
  gather_facts: yes
#  become: no
#  become_user: root
#  remote_user: osc
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc

  tasks:
  - name: "Set app_type"
    set_fact:
      app_type: "M2"

  - name: "set required percentage"
    set_fact:
      memory_percentage_required: 0.75
    tags:
      - php-fpm

  - name: "Set default php memory limit for M1 -- tags: php-fpm"
    set_fact:
       fpm_memory_limit: 512
    when:
      - app_type == "M1"
    tags:
      - php-fpm
  
  - name: "Set default php memory limit for M1 -- tags: php-fpm"
    set_fact:
       fpm_memory_limit: 768
    when:
      - app_type == "M2"
    tags:
      - php-fpm

  - name: "Get Current Memory Information -- tags: memory-cal"
    shell: grep MemTotal /proc/meminfo | awk -F" " '{print $2}'
    register: current_mem
    tags:
      - memory-cal

#  - name: "Change output to integer"
#    set_fact:
##      maxmeminfo: "{{ (((current_mem.stdout | int) / 1048576) * 0.7) | round | int }}"
##      meming: "{{ ((current_mem.stdout | int) / 1048576) | round | int }}"
##      meminm: "{{ ((current_mem.stdout | int) * 0.0009765625) | round | int }}"
#      meminm: "{{ ((current_mem.stdout | int) / 1024) | round | int }}"
#
#  - debug:
#      msg: "Memory in Integer is {{ meminm }}"
#
#  - name: "Calculating maxmeminfo"
#    set_fact:
#      maxmeminfo: "{{ ((meminm | int) * 0.70) | int }}"
#
#  - debug:
#      msg: "maxmeminfo is {{ maxmeminfo }}"


  - name: "Calculating Memory size in MB -- tags: memory-cal"
    set_fact:
        memory_cal_input: "{{ ((current_mem.stdout | int) / 1024) | round | int }}"
    tags:
      - memory-cal

  - debug:
      msg: "memory_cal_input is {{ memory_cal_input }}"
  
  - name: "Calculating {{ memory_percentage_required }}% of the memory size -- tags: memory-cal"
    set_fact:
#      memory_cal_output: "{{ ((memory_cal_input | int) * (memory_percentage_required | int)) | int }}"
      memory_cal_output: "{{ ((memory_cal_input | int) * memory_percentage_required) | int }}"
    tags:
      - memory-cal

  - debug:
      msg: "memory_cal_output is {{ memory_cal_output }}"
  
  - name: "Set max children process -- tags: php-fpm"
    set_fact:
      fpm_max_children: "{{ ((memory_cal_output | int) / fpm_memory_limit) | round | int }}"
    tags:
      - php-fpm

  - debug:
      msg: "fpm_max_children is {{ fpm_max_children }} and fpm_memory_limit is {{ fpm_memory_limit }}"

