# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

- hosts: localhost
  gather_facts: no
  become: no
  tasks:
  - set_fact: 
      client_code: LCGAH
      env_type: DMZ

  - debug:
      msg: "{{ hostvars }}"

#  - debug:
#      msg: "I'm {{ ansible_user_id }}"

  - name: "checkout {{ client_code | lower }}config"
    git:
      repo: "git@bitbucket.org:lyonsconsultinggroup/{{ client_code | lower }}config.git"
      version: master
      dest: ~/ansible/clients/{{ client_code | lower }}config
      accept_hostkey: yes
    become: yes
    become_user: rtran
