# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

- hosts: localhost
  gather_facts: no
  become: no
  tasks:

  
#  - name: "Copy package.json from the Repo"
#    get_url:
#      url: https://bitbucket.org/lyonsconsultinggroup/reference-application/raw/master/gulp_builder/package.json
#      dest: /tmp/package.json

  - name: "Get package.json"
    uri:
      url: https://bitbucket.org/lyonsconsultinggroup/reference-application/raw/master/gulp_builder/package.json
      method: GET
      body_format: raw
      dest: /tmp/package.json
      headers:
        Authorization: "Basic cnRyYW5AbHlvbnNjZy5jb206TmIwRGoxUDBoU1p5NGNK"

#      password: "{{ oscsvc_password }}"
#      force_basic_auth: yes
#      status_code: 201

#git clone git@bitbucket.org:lyonsconsultinggroup/reference-application.git
#  - name: "checkout {{ client_code | lower }}prdconfig"
#    git:
#      repo: "git@bitbucket.org:lyonsconsultinggroup/reference-application.git"
#      version: HEAD
#      dest: "./files/reference-application"
#      force: no
