# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

- hosts: localhost
  gather_facts: no
  become: no
  tasks:
  - set_fact: 
      client_code: arm

  - name: "checkout {{ client_code | lower }}prdconfig"
    git:
      repo: "git@bitbucket.org:lyonsconsultinggroup/{{ client_code | lower }}{{ item }}config.git"
      version: HEAD
      dest: "./files/{{ client_code | lower }}{{ item }}config"
      force: no
    with_items:
      - dmz
      - stg
      - prd
