# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

- hosts: localhost
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc

  tasks:
  - set_fact: 
      client_code: ANS
      env_type: PRD

  - debug:
      msg: "{{ hostvars }}"

  - debug:
      msg: "I'm {{ ansible_user_id }}"

  - name: "checkout {{ client_code | lower }}{{ env_type | lower }}config"
    git:
      repo: "git@bitbucket.org:lyonsconsultinggroup/{{ client_code | lower }}{{ env_type | lower }}config.git"
      version: master
      dest: ./files/{{ client_code | lower }}{{ env_type | lower }}config
      accept_hostkey: yes
    become: yes
    become_user: rtran
