# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

- hosts: LB
  gather_facts: yes
  become: no
  become_user: root
  remote_user: osc
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc

  tasks:
#  - name: "Get A List of directories in the Haproxy Directory"
#    find:
#      path: "/etc/haproxy"
#      recurse: yes
#      file_type: directory
#    register: haproxy_directories

#  - debug:
#      msg: "Target path is {{ item.path | basename }}"
#    with_items: "{{ haproxy_directories.files }}"
  
#  - name: "Re-create directory structure local"
#    file:
#      path: "./files/{{ item.path }}"
#      state: directory
#    delegate_to: localhost
#    with_items: "{{ haproxy_directories.files }}"
#    become: no
    
  - name: "Get A List of files in the Haproxy Directory"
    find:
      path: "/etc/haproxy"
      recurse: yes
    register: haproxy_files

  - name: "Get files"
    fetch:
      src: "{{ item.path }}"
      dest: ./files/
      flat: no
    with_items: "{{ haproxy_files.files }}"

  - name: "Get A List of files in the keepalived Directory"
    find:
      path: "/etc/keepalived"
      recurse: yes
    register: ka_files

  - name: "Get files"
    fetch:
      src: "{{ item.path }}"
      dest: ./files/
      flat: no
    with_items: "{{ ka_files.files }}"
