# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

#- hosts: DB:WEB
- hosts: DB
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc

  tasks:
  - name: What is my hostname
  
# Get master binlog file name and binlog position
  - name: Get binlog info Master {{ repl_primary }}
    mysql_replication:
      mode: getmaster
      login_user: root
      login_password: "{{ mysql_root_password }}"
    register: mysql_master_primary
    delegate_to: "{{ repl_primary }}"
    tags:
      - mysql-replication
    when:  replication_role | match ("secondary")

  - name: Get binlog info Secondary {{ repl_secondary }}
    mysql_replication:
      mode: getmaster
      login_user: root
      login_password: "{{ mysql_root_password }}"
    register: mysql_master_secondary
    delegate_to: "{{ repl_secondary }}"
    tags:
      - mysql-replication
    when:  replication_role | match ("primary")

  - debug:
      msg: "{{ mysql_master_primary }}"

  - debug:
      msg: "{{ mysql_master_secondary }}"
