- hosts: localhost
  become: no
  gather_facts: no
  tasks:

  - name: Pull in oscsvc password
    include_vars: oscsvc.yml

  - name: Create a JIRA issue
    uri:
      url: "https://lyonscg.atlassian.net/rest/api/2/issue/"
      method: POST
      user: oscsvc
      password: "{{ oscsvc_password }}"
      body: "{{ lookup('file','./issue.json') }}"
      force_basic_auth: yes
      status_code: 201
      body_format: json
