# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

- hosts: M1DD
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc
  tasks:
  - name: Create temp directory to hold data
    file:
      path: /tmp/m1dd_data
      state: directory
    delegate_to: localhost
  - name: Check to see if deployment dashboard site already exists
    stat:
      path: /etc/apache2/sites-available/capapp.conf
    register: capapp
  - name: Tag dd info
    file:
      path: /tmp/m1dd_data/capapp_exists
      state: touch
    delegate_to: localhost
    when: capapp.stat.exists == True
  - name: Check to see if deploy user already exists
    command: bash -c "/usr/bin/getent passwd deploy | wc -l"
    register: deploy_user
  - name: Tag deploy user info
    file:
      path: /tmp/m1dd_data/deployuser_exists
      state: touch
    delegate_to: localhost
    when: deploy_user.stdout == "1"
  - name: Get ssh pub cred
    fetch:
      src: /home/deploy/.ssh/{{ item }}
      dest: /home/deploy/.ssh/
      flat: yes
    with_items:
      - id_rsa.pub
      - id_rsa
      - authorized_keys
      - known_hosts
    when: deploy_user.stdout == "1"
  - name: Deploment dashboard exists?
    stat:
      path: /tmp/m1dd_data/capapp_exists
    register: dd_exits
