# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

#- hosts: DB:WEB
- hosts: DB
  gather_facts: no
#  become: no
#  become_user: root
#  remote_user: osc
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc

  tasks:
  - name: Creating a random 16 character password 
#    shell: "pwgen -C -n 16 1 > /tmp/ka_passwd.txt.$(date +\"%Y%m%d_%H%M%S\""
    command: "/usr/bin/pwgen -C -n 16 1"
    register: passwd
    run_once: true
    delegate_to: localhost
    tags:
      - keepalived

#  - name: Getting the password 
#    command: "cat /tmp/ka_passwd.txt"
#    register: passwd_content
#    delegate_to: localhost

  - name: Set Variable
    set_fact: 
      auth_pass: "{{ passwd.stdout }}"
    run_once: true

  - debug:
#      msg: "{{ passwd.stdout }}"
      msg: "{{ auth_pass }}"
