# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

#- hosts: DB:WEB
- hosts: DB
  gather_facts: no
#  become: no
#  become_user: root
#  remote_user: osc
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc

  tasks:

  - set_fact:
      my_current_vlan=10.0.78.

  - debug: 
      msg: "My item is {{ item }}"
    with_items:
      - "{{ my_current_vlan }}.4% }}"
      - "{{ my_current_vlan }}.5% }}"
      - "{{ my_current_vlan }}.6% }}"

    
