- hosts: all
  become: yes
#  become_method: sudo
  become_user: root
  remote_user: osc
  gather_facts: no
  tasks:

#  - name: Store deploy user's ssh keys locally temporary
#    fetch:
#      src: /home/deploy/.ssh/{{ item }}
#      dest: /home/osc/deploy_ssh/
#      flat: yes
#    with_items: 
#      - id_rsa
#      - id_rsa.pub
#      - authorized_keys
  - name: Create deploy user
    user:
      name: deploy
      uid: 1001
      state: present

  - name: Generate temp rsa keys for local deploy user
    user:
      name: deploy
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    delegate_to: localhost 

  - name: Copy rsa keys 
    copy:
      src: /home/deploy/.ssh/id_rsa
      dest: /home/deploy/.ssh/
      mode: 600

  - name: Copy rsa public keys 
    copy:
      src: /home/deploy/.ssh/id_rsa
      dest: /home/deploy/.ssh/
      mode: 644

#  - name: Copy osc public key to server
#    authorized_key:
#      user: osc
#      key: "{{ lookup('file', '/home/deploy/.ssh/id_rsa.pub') }}"
#      state: present

