# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

- hosts: DB
#- hosts: all
  gather_facts: no
#  become: no
#  become_user: root
#  remote_user: osc
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc

  tasks:
    - name: check disk partition
      command: fdisk -l /dev/sdb1
      register: fdisk_out
      ignore_errors: yes

    - debug:
        msg: "error message is {{ fdisk_out.stderr  }}"
      when: fdisk_out.stderr | match("fdisk*")

    - debug:
        msg: "sdb exists because there are no errors"
      when: fdisk_out.stderr == ""

    - name: check physical volume 
      command: pvdisplay -m /dev/sdb1
      register: pvstat
      when: fdisk_out.stderr == ""

    - debug:
        msg: "sdb is part of the lvm physical volume"
      when: fdisk_out.stderr == "" and pvstat.stderr == ""
