# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

#- hosts: DB:WEB
- hosts: TEST
  gather_facts: yes
#  become: no
#  become_user: root
#  remote_user: osc
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc

  tasks:
  - name: "Fetching and unpacking ionCube tarball -- tags: php, ioncube"
    unarchive:
      src: http://downloads2.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
      dest: /tmp/
      owner: root
      group: root
      mode: 0755
      remote_src: yes
      creates: /tmp/ioncube_loader_lin_5.3.so
    tags:
      - php
      - ioncube
