# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

#- hosts: DB:WEB
- hosts: all
  gather_facts: no
#  become: no
#  become_user: root
#  remote_user: osc
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc

  tasks:
  - name: Set client code
    set_fact: client_code=ARM
  
  - name: Set environment
    set_fact: env_type=STG

  - name: Put it all-together
    set_fact: all="{{ client_code }}-{{ env_type }}-PROXY"

  - name: show me the money 
    debug:
      msg: "{{ all }}"

 
