# To run this playbook, use the following command and your credentials for loggin in:
#    ansible-playbook chrootpasswd.yml -Kk -i hosts.ini
# When prompted, enter new password

#- hosts: DB:WEB
- hosts: WEB
  gather_facts: yes
#  become: no
#  become_user: root
#  remote_user: osc
  become: yes
  become_user: root
  become_method: sudo
  remote_user: osc


  tasks:
  - meta: end_play
  when: "{{ groups['LB'] | map('extract',hostvars,'keepalive_vip') | first }}" is undefined


  - name: Running Command for VLAN
    set_fact: 
      lb_vip: "{{ groups['LB'] | map('extract',hostvars,'keepalive_vip') | first }}"

  - debug:
      msg: "my LB keepalive is {{ lb_vip }}"
