---
# roles/db-passwd-manager/tasks/main.yml
# tasks to write adn read mysql creds 

- name: "Determine if variable file exists -- tags: db-passwd-manager"
  stat:
    path: "/usr/local/ansible/mysql/{{ client_code }}_mysql_creds.yml"
  register: var_file
  delegate_to: localhost 
  become: no
  tags:
    - db-passwd-manager

- debug:
    msg: "MySQL creds file /usr/local/ansible/mysql/{{ client_code }}_mysql_creds.yml for client {{ client }} doesn't exists"
  when: var_file.stat.exists == False
  tags:
    - db-passwd-manager

- debug:
    msg: "MySQL creds for client {{ client }} exists"
  when: var_file.stat.exists == True
  tags:
    - db-passwd-manager

- name: "Get the variables from an existing file -- tags: db-passwd-manager"
  include_vars: "/usr/local/ansible/mysql/{{ client_code }}_mysql_creds.yml"
  when: var_file.stat.exists == True
  tags:
    - db-passwd-manager

#- meta: end_play
#  when: var_file.stat.exists == True
#  tags:
#    - db-passwd-manager

- name: Creating root password for production
  command: "/usr/bin/pwgen -C -n 18 1"
  register: tmp_prd_root_password
  delegate_to: localhost 
  become: no
  when: var_file.stat.exists == False
  tags:
    - db-passwd-manager

- name: Creating dbuser password for production
  command: "/usr/bin/pwgen -C -n 18 1"
  register: tmp_prd_dbuser_password
  delegate_to: localhost 
  become: no
  when: var_file.stat.exists == False
  tags:
    - db-passwd-manager

- name: Creating replication user repl password for production
  command: "/usr/bin/pwgen -C -n 8 1"
  register: tmp_prd_repluser_password
  delegate_to: localhost 
  become: no
  when: var_file.stat.exists == False
  tags:
    - db-passwd-manager

- name: Creating root password for dev and stage
  command: "/usr/bin/pwgen -C -n 18 1"
  register: tmp_devstg_root_password
  delegate_to: localhost 
  become: no
  when: var_file.stat.exists == False
  tags:
    - db-passwd-manager

- name: Creating root password for dev and stage
  command: "/usr/bin/pwgen -C -n 18 1"
  register: tmp_devstg_dbuser_password
  delegate_to: localhost 
  become: no
  when: var_file.stat.exists == False
  tags:
    - db-passwd-manager

- name: Creating replication user repl password for dev and stage
  command: "/usr/bin/pwgen -C -n 8 1"
  register: tmp_devstg_repluser_password
  delegate_to: localhost 
  become: no
  when: var_file.stat.exists == False
  tags:
    - db-passwd-manager

- name: Creating the variable file
  template:
    src: mysql_creds.yml.j2
    dest: "/usr/local/ansible/mysql/{{ client_code }}_mysql_creds.yml"
    group: lyonscg_ah
    mode: 0660
  delegate_to: localhost 
  become: no
  when: var_file.stat.exists == False
  tags:
    - db-passwd-manager

- name: "Get the variables from an existing file -- tags: db-passwd-manager"
  include_vars: "/usr/local/ansible/mysql/{{ client_code }}_mysql_creds.yml"
  tags:
    - db-passwd-manager
