---
# web-php/tasks/main.yml

- name: "Checking PHP processor option -- tags: php-fpm"
  fail: msg="Required php_processor {{ php_processor }} is invalid. Please enter mod_php or PHP-FPM"
  when: not (php_processor | match("PHP-FPM|mod_php"))
  tags:
    - php-fpm

# Set php memory allocation 
- name: "Set default php memory limit for M1 -- tags: php-fpm"
  set_fact:
     fpm_memory_limit: 512
  when:
    - app_type == "M1"
  tags:
    - php-fpm
    - web-php

- name: "Set default php memory limit for M2 -- tags: php-fpm"
  set_fact:
     fpm_memory_limit: 768
  when:
    - app_type == "M2"
  tags:
    - php-fpm
    - web-php

- name: "Run multi-memory-cal to get memory configuration -- tags: php-fpm"
  include_role:
    name: multi-memory-cal
  vars:
    memory_percentage_required: 0.75
  when:
    - php_processor == "PHP-FPM"
  tags:
    - php-fpm
    - web-php

- name: "Set max children process -- tags: php-fpm"
  set_fact:
    fpm_max_children: "{{ ((memory_cal_output | int) / fpm_memory_limit) | round | int }}"
  when:
    - php_processor == "PHP-FPM"
  tags:
    - php-fpm
    - web-php

- debug:
    msg: "fpm_max_children is {{ fpm_max_children }} and fpm_memory_limit is {{ fpm_memory_limit }}"
  when:
    - php_processor == "PHP-FPM"
  tags:
    - php-fpm
    - web-php

- name: "Install mod_php 5.5 on Ubuntu 14.04"
  include: php-{{ ansible_distribution }}_{{ ansible_distribution_release }}-{{ php_processor }}.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty' and php_processor == 'mod_php'

- name: "Install mod_php 7.0 on Ubuntu 16.04"
  include: php-{{ ansible_distribution }}_{{ ansible_distribution_release }}-{{ php_processor }}.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial' and php_processor == 'mod_php'

- name: "Install mod_php 5.3 on CentOS 6"
  include: php-{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: "Install PHP-FPM 5.5 on Ubuntu 14.04"
  include: php-{{ ansible_distribution }}_{{ ansible_distribution_release }}-{{ php_processor }}.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty' and php_processor == 'PHP-FPM'

- name: "Install PHP-FPM 7.0 on Ubuntu 16.04"
  include: php-{{ ansible_distribution }}_{{ ansible_distribution_release }}-{{ php_processor }}.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial' and php_processor == 'PHP-FPM'
