---
# web-php/tasks/php-Ubuntu_trusty_mod_php.yml
- name: "Installing PHP -- tags: muti-php-install"
  apt:
    update_cache: yes
    cache_valid_time: 43200
    state: installed
    name: "{{ item }}"
  async: 300
  poll: 15
  with_items:
    - libapache2-mod-php5
    - mysql-client-5.6
    - php5
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-mysql
    - php5-readline
    - php5-xmlrpc
    - php-pear
    - php-soap
  notify:
    - restart apache
  tags:
    - php-install

- name: "Enabling Apache PHP module -- tags: php-install"
#  apache2_module:
#    state: present
#    name: php5
#    ignore_configcheck: yes
#  notify:
#    - restart apache
  command: "/usr/sbin/a2enmod {{ item }}"
  with_items:
      - php5
  notify:
    - restart apache
  tags:
    - php-install

- name: "Enabling PHP mcrypt module -- tags: php-install"
  command: php5enmod mcrypt
  notify:
    - restart apache
  tags:
    - php-install

- name: "Copying Apache php.ini -- tags: php-install"
  copy:
    src: php.ini
    dest: /etc/php5/apache2/php.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache
  tags:
    - php-install

- name: "Copying CLI php.ini -- tags: php-install"
  copy:
    src: php.ini
    dest: /etc/php5/cli/php.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache
  tags:
    - php-install
