---
# db-mysql-install/tasks/main.yml
# Last updated by Darius McCaskey

# Pull in the credentials
#- name: Get the variables from an existing file
#  include_vars: "/usr/local/ansible/mysql/{{ client_code }}_mysql_creds.yml"
#  tags:
#    - mysql-install

- name: Set the root password for Dev and Stage
  set_fact: 
    mysql_root_password: "{{ devstg_root_password }}"
  when: env_type | match("DEV|STG")
  tags:
    - mysql-install

- name: Set the root password for Production
  set_fact: 
    mysql_root_password: "{{ prd_root_password }}"
  when: env_type | match("PRD")
  tags:
    - mysql-install

- name: Determine if my.cnf file exists
  stat:
    path: "/root/.my.cnf"
  register: my_cnf

- name: Create my.cnf file
  template:
    src: my.cnf.j2
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
    force: yes
    backup: yes

# Preliminary work to get info from the hostname
- set_fact:
    last_digit_hostname_work: |
      {{ hostvars[inventory_hostname].ansible_hostname.split('-')[3] | map('regex_replace','^0','') | list}}
  tags:
    - mysql-install

- set_fact:
    server_id: "{{ last_digit_hostname_work[1] }}"
  tags:
    - mysql-install

- name: "Install MySQL 5.6 on Ubuntu 14.04"
  include: mysql-{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags:
    - mysql-install

- name: "Install MySQL 5.7 on Ubuntu 16.04"
  include: mysql-{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
  tags:
    - mysql-install

- name: "Install MySQL 5.6 on CentOS 6"
  include: mysql-{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
  tags:
    - mysql-install
